### PR TITLE
Use the right door attribute

### PR DESCRIPTION
**Pull request by RomainGx**
Fix for doors sensor with intrusionDetect attribute: choose the right attribute to create the sensor.

**Question : How do you proceed to test your modifications before merging them to master?
I would like to test these ones in order to be sure I didn't forget anything.**

### CODE REVIEW

**Comment by mrwiwi** [comment]
I just sync and python3 the script, by modifying the main script with my credentials and data :) I don't have a lot of time so i test pretty rapidly, and i don't have a lot of devices so i pretty much trust you guys :)

**Comment by RomainGx** [comment]
> I just sync and python3 the script, by modifying the main script with my credentials and data :) I don't have a lot of time so i test pretty rapidly, and i don't have a lot of devices so i pretty much trust you guys :)

Ok thanks. I close this issue since I will propose a big refactor next time

**Comment by mrwiwi** [comment]
You mean of the entire project ? :)

**Comment by RomainGx** [comment]
> You mean of the entire project ? :)

Yes :)

I can test doors, windows and alarm, but I will need other people to test lights and boiler :)

In a few weeks I hope, but it will depend on the birthdate of my child :)

**Comment by mrwiwi** [comment]
If you need inspiration, very good coding here : https://github.com/mgcrea/homebridge-tydom

I was thinking of sharing the ownership the project, I can't touch it easily for now (my wife just got out of cancer, and the 5 year old is still 5 years old ;))

And I'm still an amateur !

**Comment by RomainGx** [comment]
> 
> 
> If you need inspiration, very good coding here : https://github.com/mgcrea/homebridge-tydom
> 
> I was thinking of sharing the ownership the project, I can't touch it easily for now (my wife just got out of cancer, and the 5 year old is still 5 years old ;))
> 
> And I'm still an amateur !

Thanks for what you've already done, that's really great!

**Pull request closed without merging**
